name: Rebase
on:
  workflow_dispatch: # run manually
  schedule:
  - cron: "0 0 * * *" # run once a day

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
      with:
        fetch-depth: 0
    - name: Rebase against nixos-unstable
      uses: imba-tjd/rebase-upstream-action@0.5
      with:
        upstream: NixOS/nixpkgs
        branch:   nixos-unstable
        depth: 0
